# engine_adapter.py

from gis_engine.engine import GISEngine


class EngineAdapter:
    """
    Bridge between LLM workflow and GIS Engine execution.
    """

    def __init__(self):
        self.engine = GISEngine()

    def run_workflow(self, workflow_json):
        """
        Execute workflow generated by LLM.
        """
        result = self.engine.run_workflow(workflow_json)
        return result