class GISEngine:

    def __init__(self, logger=None):
        from .core import WorkflowExecutor, StepRegistry, ContextManager
        from .utils import Logger

        self.logger = logger or Logger("gis_engine")
        self.logger.setup()

        self.registry = StepRegistry()
        self.context = ContextManager()
        self.executor = WorkflowExecutor(self.registry)

        self._register_default_steps()

    # def _register_default_steps(self):
    #     """
    #     Register all built-in processing steps here.
    #     """
    #     from .steps import (
    #         ThresholdStep,
    #         ReclassifyStep,
    #         SlopeStep,
    #         ReadRasterStep,
    #         ReadVectorStep
    #     )

    #     self.registry.register("threshold", ThresholdStep)
    #     self.registry.register("reclassify", ReclassifyStep)
    #     self.registry.register("calculate_slope", SlopeStep)
    #     self.registry.register("read_raster", ReadRasterStep)
    #     self.registry.register("read_vector", ReadVectorStep)
        
    def _register_default_steps(self):
   
        from .analysis.threshold import ThresholdStep
        from .raster.reclassify import ReclassifyStep
        from .raster.slope import SlopeStep
        from .raster.dem import ReadRasterStep
        from .vector.osm_loader import ReadVectorStep
        from .analysis.extraction import ExtractTopLocationsStep

        self.registry.register("threshold", ThresholdStep)
        self.registry.register("reclassify", ReclassifyStep)
        self.registry.register("calculate_slope", SlopeStep)
        self.registry.register("read_raster", ReadRasterStep)
        self.registry.register("read_vector", ReadVectorStep)
        self.registry.register("ExtractTopLocations", ExtractTopLocationsStep)

    def run_workflow(self, workflow_json):
        """
        Execute workflow generated by LLM.
        """
        self.executor.steps = []

        steps = workflow_json.get("steps", workflow_json) if isinstance(workflow_json, dict) else workflow_json

        for step in steps:
            self.executor.add_step(step)

        return self.executor.execute(self.context)